# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# update_fastlane

default_platform(:android)



platform :android do
  desc "Submit a new Beta Build to Play Store"

  lane :increment_build_number do
    increment_build_number(build_number: ENV['CI_BUILD_ID'])
  end
  lane :beta do
    # increment_version_code(gradle_file_path: "app/build.gradle")
    # changelog_from_git_commits
    # gradle(task: "clean assembleRelease")
    upload_to_play_store(
      track: 'beta',
      apk: 'app/build/outputs/apk/release/app-release.apk'
    )
  
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
