# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Play Store"

  lane :increment_build_number do
    # increment_build_number(build_number: ENV['CI_BUILD_ID'])
    increment_version_code(gradle_file_path: "app/build.gradle")

    #Commit the version bump to git, and tag the commit with the release version and push
    git_commit(
      path: File.dirname("app/build.gradle"),
      message: "Upgrated version code"
    )
    push_to_git_remote
  end

  lane :beta do
    # changelog_from_git_commits
    # gradle(task: "clean assembleRelease")
    upload_to_play_store(
      track: 'beta',
      apk: 'app/build/outputs/apk/release/app-release.apk'
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
