# Baldissera image of android container.
image: baldissera/android-container:1.0

variables:
  DOCKER_DRIVER: overlay2
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - export ANDROID_HOME="/usr/local/android-sdk"
  - cd project

stages:
  - test
  - build
  - deploy

# static_analysis:
#   stage: test
#   script:
#     - mv ../docker/static_analysis.sh ./static_analysis.sh
#     - chmod +x ./static_analysis.sh
#     - ./static_analysis.sh

# unit_test:
#   stage: test
#   script:
#     - mv ../docker/test.sh ./test.sh
#     - chmod +x ./test.sh
#     - ./test.sh
#   artifacts:
#     name: "reports_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}_unit_test"
#     when: always
#     expire_in: 2 days
#     paths:
#       - project/app/build/reports/jacocoTestReport/html

# instrumentation_tests:
#   stage: test

build:
  stage: build
  before_script:
    - export ANDROID_HOME="/usr/local/android-sdk"
    - export $API_KEY
    - cd project
    - git clone $KEY_STORE_REPO ./key
    - mv ./key/$STORE_FILE ./app/
    - rm -Rf ./key
    - git config --global user.email "guilhermebaldissera@hotmail.com"
    - git config --global user.name "Baldissera"
  script:
    - mv ../docker/build.sh ./build.sh
    - chmod +x ./build.sh
    - fastlane update_build_number
    - ./build.sh
  after_script:
    - rm -Rf ./app/.git/
    - rm ./app/$STORE_FILE
  artifacts:
    paths:
    - project/app/build/outputs/apk
  # only:
    # - tags
    # - dev
    # - master

deploy_beta:
  stage: deploy
  before_script:
    - cd project
    - echo $DEPLOY_KEY_FILE >> key.json
  script:
    - fastlane beta
  after_script:
    - rm key.json
  dependencies:
    - build
  artifacts:
    paths:
      - fastlane/logs
  # only:
    # - tags

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/
