# Baldissera image of android container.
image: baldissera/android-container

variables:
  DOCKER_DRIVER: overlay2
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - export ANDROID_HOME="/usr/local/android-sdk"
  - cd project
  # - echo $KEYSTORE_PROPERTIES >> project/keystore.properties

after_script:
  # - rm project/keystore.properties

stages:
  - test
  - build
  - deploy

static_analysis:
  stage: test
  script:
    - mv ../docker/static_analysis.sh ./static_analysis.sh
    - chmod +x ./static_analysis.sh
    - ./static_analysis.sh

unit_test:
  stage: test
  script:
    - mv ../docker/test.sh ./test.sh
    - chmod +x ./test.sh
    - ./test.sh
  artifacts:
    name: "reports_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}_unit_test"
    when: always
    expire_in: 2 days
    paths:
      - project/app/build/reports/jacocoTestReport/html

# instrumentation_tests:
#   stage: test

build:
  stage: build
  before_script:
    - git clone $KEY_STORE_REPO ./app
  script:
    - mv ../docker/build.sh ./build.sh
    - chmod +x ./build.sh
    - ./build.sh
  after_script:
    - rm -Rf ./app/.git/
    - rm ./app/$STORE_FILE
  artifacts:
    paths:
    - project/app/build/outputs/apk

deploy_beta:
  stage: deploy
  before_script:
    - gem install bundler
    - bundle install
    - echo $DEPLOY_KEY_FILE >> key.json
  script:
    - cd project
    - bundle exec fastlane beta
  after_script:
    - rm key.json
  dependencies:
    - build
  artifacts:
    paths:
      - fastlane/logs

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - /root/.gradle/
