# Official docker image.
image: docker:latest

variables:
  ANDROID_CONTAINER_IMAGE: baldissera/android-container

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker pull $ANDROID_CONTAINER_IMAGE:latest
    - docker-compose up
