# Official docker image.
image: docker:latest

variables:
  ANDROID_CONTAINER_IMAGE: baldissera/android-container

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker run -v $(pwd)/project:/application -v $(pwd)/local.properties.env:/application/local.properties $ANDROID_CONTAINER_IMAGE:latest
