site_name: nexte
site_description: 'Aplicativo que integra tenistas dentro de clubes, por meio de partidas e desafios, juntando estatísticas e gamificação em forma de ranking. Tem como objetivo gamificar comunidades locais de tênis.'
repo_url: https://github.com/fga-gpp-mds/2018.1_Nexte
theme: readthedocs

pages:
  - Home: index.md
  - Estudos: 
    - Centralização de Informações: CentralizacaoInformacoes.md
  - EPS:
    - Termo de abertura: EPS/TAP.md
    - Estrutura analítica do projeto: EPS/EAP.md
    - AgileEVM: EPS/AgileEVM.md
    - ROADMAP: EPS/RoadMap.md
    - Metodologia: EPS/MetodologiaDoProjeto.md
    - Politica de Branches: EPS/PoliticaDeBranches.md
    - Definição de Pronto: EPS/Definicao-de-Pronto.md
    - Arquitetura de Microserviços: EPS/ArquiteturaMicroservicos.md
    - Gestão de Risco: EPS/GestaoDeRisco.md
    - Definição de Produtividade: EPS/DefinicaoDeProdutividade.md
    - Canvas: EPS/Canvas.md
    - Plano de Qualidade:
      - Abtraction Sheet: EPS/PlanoDeQualidade/AbstractionSheet.md
      - GQM: EPS/PlanoDeQualidade/GQM.md
      - Métricas: EPS/PlanoDeQualidade/Metricas.md
      - Objetivos: EPS/PlanoDeQualidade/Objetivos.md
      - Questões: EPS/PlanoDeQualidade/Questoes.md
  - MDS:
    - Documento de visão: MDS/DocVisao.md
    - Documento de arquitetura: MDS/DocArquitetura.md
    - Especificação Suplementar: MDS/DocEspecificacaoSuplementar.md
    - Protótipo de Baixa Fidelidade: MDS/DocPrototipodeBaixaFidelidade.md
    - Folha de Estilo: MDS/DocFolhaEstilo.md
 
  - Sprint 0:
    - Planejamento: Sprints/Sprint0/Sprint0-Planejamento.md
    - Resultado: Sprints/Sprint0/Sprint0-Resultados.md
  - Sprint 1:
    - Planejamento: Sprints/Sprint1/Sprint1-Planejamento.md
    - Resultado: Sprints/Sprint1/Sprint1-Resultados.md
  - Sprint 2:
    - Planejamento: Sprints/Sprint2/Sprint2-Planejamento.md
    - Resultado: Sprints/Sprint2/Sprint2-Resultados.md
  - Sprint 3:
    - Planejamento: Sprints/Sprint3/Sprint3-Planejamento.md
    - Resultado: Sprints/Sprint3/Sprint3-Resultados.md
  - Sprint 4:
    - Planejamento: Sprints/Sprint4/Sprint4-Planejamento.md
    - Resultado: Sprints/Sprint4/Sprint4-Resultados.md
  - Sprint 5:
    - Planejamento: Sprints/Sprint5/Sprint5-Planejamento.md
    - Resultados: Sprints/Sprint5/Sprint5-Resultados.md
  - Sprint 6:
    - Planejamento: Sprints/Sprint6/Sprint6-Planejamento.md
    - Resultados: Sprints/Sprint6/Sprint6-Resultados.md
  - Sprint 7:
    - Planejamento: Sprints/Sprint7/Sprint7-Planejamento.md
    - Resultados: Sprints/Sprint7/Sprint7-Resultados.md
  - Post Mortem:
    - Post Mortem - Release 1: PostMortem/PostMortemRelease1.md
